### ISSUE TITLE
How to exclude Node.js?

### ISSUE THREAD

**Issue by zoechi** [sapegin/textlint-rule-terminology#24]
I tried

```
"terminology": {
      "defaultTerms": true,
      "exclude": [
        "Node(?:js)?",
        "node"
      ]
    },
```
Where `"Node(?:js)?"` is the regex from the `defaultTerms` and `node` the word in my text, but both didn't work.

**Comment by sapegin** [comment]
Looks like it doesn't work with arrays now, feel free to send a pull request.

https://github.com/sapegin/textlint-rule-terminology/blob/c982c7fda84f6c558b6465d6aa94bda91172e679/index.js#L98

**Comment by zoechi** [comment]
I won't be able anytime soon, but at least if someone else runs into it, he might find this info. I'm just checking out textlnit. I might invest more time when I decide to actually use it.

**Comment by Mister-Hope** [comment]
Same issue here.
