### ISSUE TITLE
Enhancement request: Warn terms/conditions

### ISSUE THREAD

**Issue by kingthorin** [sapegin/textlint-rule-terminology#25]
Would you consider adding some sort of terminology warn list?

I'm thinking of two use cases that I've encountered lately, I'm sure there are others.

1. Use of 'Open Source' should often (but not always) be in title caps. (Ref: https://perens.com/2017/09/26/on-usage-of-the-phrase-open-source/)
1. I've seen this typo a number of times lately, where people end-up with 'formally' when they mean 'formerly' (likely a auto-correct/predictive text issue). However, neither word is misspelled when used correctly/contextually.

It would be good if there was some sort of warning handling to get people to have a second look at such occurrences...

Obviously `--fix` can't do anything about these, but as long as there was some output that'd be sufficient.

Let me know what you think.

**Comment by sapegin** [comment]
You could add these terms to your config file, not sure what else we can do in the plugin itself.

**Comment by kingthorin** [comment]
We don’t want them to just be assumed wrong though.

I guess really I’m asking for new functionality in the plugin 🙂

**Comment by sapegin** [comment]
I'm sure there are more suitable plugins for such cases — this plugin doesn't try to cover all possible use cases.

**Comment by kingthorin** [comment]
Okay that's fair. Thanks!
