### ISSUE TITLE
Allow a term to appear only defined amount of times?

### ISSUE THREAD

**Issue by bebraw** [sapegin/textlint-rule-terminology#3]
Example: allow "I" to appear in the whole text only 3 times.

**Comment by sapegin** [comment]
I think general writing rules like avoiding certain words or maximum number of usages in a sentence / paragraph is out of scope of this rule. But we can think about a new one ;-)

One caveat: textlint returns partial paragraphs (like before link, inside link, after link) so it might be tricky to make such a rule.

**Comment by bebraw** [comment]
https://github.com/azu/textlint-rule-en-max-word-count does this per sentence. I was thinking a global check (against whole content).

**Comment by sapegin** [comment]
This [Syntax.Paragraph](https://github.com/azu/textlint-rule-en-max-word-count/blob/master/src/textlint-rule-en-max-word-count.js#L28) maybe a key if they have something with a bigger scope. We use `Syntax.Str` here.

**Comment by sapegin** [comment]
I think this is out of the scope of this rule. It would be better to improve textlint-rule-en-max-word-count or create a new rule.
