### ISSUE TITLE
Allow skipping rules based on context

### ISSUE THREAD

**Issue by bebraw** [sapegin/textlint-rule-terminology#4]
Example: `You may need an appropriate loader to handle this file type.`. I would like to capture all other "may"s except this one.

**Comment by sapegin** [comment]
Does textlint have something for that?

**Comment by bebraw** [comment]
I'm not sure. I'll spend some time with this. Just realized having file based ignores would come in handy too.

**Comment by sapegin** [comment]
I think this is out of the scope of this rule. There’s [textlint-filter-rule-comments](https://github.com/textlint/textlint-filter-rule-comments) to disable rules for a paragraph but nothing that would work inline as far as I know.
