### ISSUE TITLE
Ignore check on certain condition

### ISSUE THREAD

**Issue by svx** [sapegin/textlint-rule-terminology#5]
Example:

You check the right spelling of ``GitHub``

```js
{
  "rules": {
    "terminology": {
      // Load default terms (see terms.json in the repository)
      "defaultTerms": true,
      // Syntax elements to skip. Overrides the default
      "skip": ["Blockquote"],
      // List of terms
      "terms": [
        // Exact spelling including the case
        "JavaScript",
        "ESLint",
        "Sass",
        "Less",
        "npm",
        "GitHub",
        // RegExp (case-insensitive) → replacement
        ["front[- ]end(\\w*)", "frontend$1"],
        ["back[- ]end(\\w*)", "backend$1"],
        ["web[- ]?site(s?)", "site$1"],
        ["hot[- ]key", "hotkey"],
        ["repo\\b", "repository"],
        ["CLI tool(s?)", "command line tool$1"],
        ["build system(s?)", "build tool$1"],
        ["id['’]?s", "IDs"],
        ["(\\w+[^.?!]\\)? )webpack", "$1webpack"],
        ["(\\w+[^.?!]\\)? )internet", "$internet"]
      ],
      // OR load terms from a file
      "terms": "~/terms.json",
      // OR load terms from npm
      "terms": "@johnsmith/terms"
    }
  }
}
```

Now imagine you have a link to a GitHub repository:

```rst

For questions, please open an issue in our `tracker <https://github.com/example/issues>`_.
```

Running textlint will report that  *github* (from the link) is not OK.
Is there a way to change the configuration to ignore, words if they are for example (like here) part of a link ?

**Comment by sapegin** [comment]
First, it’s not a link, it’s a code block. 

And there’s a `skip` option which skips only blockquotes by default, which is not the best value I think. We should probably add code as well.

**Comment by sapegin** [comment]
Feel free to send a pull request for that ;-)

**Comment by svx** [comment]
Hi,

I just used a code-block to highlight reST syntax :) 

I am sorry if that lead to confusions or misunderstanding, my intension is to skip if the word is part of a link like for example https://github.com, here I want to skip the test.

Links in reST are not code blocks, they are quoted -> http://docutils.sourceforge.net/docs/user/rst/quickref.html#hyperlink-targets

:)

**Comment by sapegin** [comment]
Do Textlint support reST? Otherwise it would be hard to distinguish links from the rest of the text.

**Comment by svx** [comment]
Yes, there is a plugin: https://github.com/jimo1001/textlint-plugin-rst

It is working really well. We use that to run reST validation checks against documentation.

**Comment by sapegin** [comment]
Then the `skip` option should work, you just need to find what value to use ;-)

**Comment by svx** [comment]
Ok thanks ! I will have a look ! :)

**Comment by sapegin** [comment]
Closing this for now. Feel free to reopen if you still have this issue.
