### ISSUE TITLE
Is it possible to exclude some terms from the config?

### ISSUE THREAD

**Issue by pixelastic** [sapegin/textlint-rule-terminology#8]
Hello,

I've been trying to exclude some default transformation from the default list (namely, I don't want to transform `websites` into `sites`). I tried to achieve this goal by tweaking the `terms` key, but manage to have any impact.

Another viable solution might be to publish my own list on npm as you suggest on the README, but I could not find any definition of the format of this list. Should it be a simple JSON file?

**Comment by sapegin** [comment]
Yeah, `terms` is appending words to the default list, so you can't really remove anything.

Yeah, the format is the same as [the default one](https://github.com/sapegin/textlint-rule-terminology/blob/master/terms.json).

Fee free to send a pull request with some ignore option, it may be simpler than publishing and maintaining your own list.

**Comment by pixelastic** [comment]
Thanks for the input. I've settled on storing my own terms file in my repo for the time being.

I did published my own list, but could not manage to import it. Would you have an example of a published external term list and how I could use it?

**Comment by sapegin** [comment]
I'm looking at the code, and I think it should be `require.resolve` instead of `path.resolve`:

https://github.com/sapegin/textlint-rule-terminology/blob/7fe73e048205904785735c03c471e21bcdebd72c/index.js#L73

**Comment by pixelastic** [comment]
I won't have the bandwidth to test and fix this at the moment unfortunately. I ended up using my own JSON list of terms in the repo, which works perfectly and is easier to maintain for us than an external list.
